# Liste des exercices du TP — données pures

EXERCISES = [
    {
        "id": "ex1", "code_label": "Ta fonction is_game_over()", "num": "1",
        "title": "Est-ce que la partie est terminée ?",
        "unlock_after": None,
        "has_launch": False,
        "instructions": [
            "Notre implémentation du jeu possède les caractéristiques suivantes :",
            "• Il y a trois poteaux : <code>A</code>, <code>B</code> et <code>C</code>.",
            "• Le poteau de départ sur lequel sont disposés tous les disques est le poteau <code>A</code>.",
            "• On souhaite déplacer la tour du poteau <code>A</code> vers le poteau <code>B</code> ou <code>C</code>.",
            "",
            "On va commencer par <b>implémenter</b> la fonction qui dit si oui ou non la partie est finie.",
            "On considère ici que la partie est terminée lorsque tous les disques sont soit sur le poteau <code>B</code>, soit sur le poteau <code>C</code>.",
            "",
            "La fonction attend <b>un paramètre</b> :",
            "• <code>poles</code> — les poteaux, qui contiennent des informations sur l'état du jeu.",
            "",
            "Elle <b>retourne</b> un booléen : <code>True</code> si la partie est terminée, <code>False</code> sinon.",
            "",
            "<b>Exemple de code utile :</b>",
            "<code>poles['A'].num_disks</code> → vaut le nombre de disques présents sur le poteau A.",
            "S'il y a 3 disques sur le poteau A, cette expression vaut <code>3</code>.",
        ],
        "starter": "def is_game_over(poles):\n    # Écrire votre code en dessous de ce commentaire.\n    pass\n",
        "check_setup": "from tests import check_is_game_over\nfrom engine import Pole, Disk",
        "check_call":  "check_is_game_over(is_game_over)",
        "needs": [],
    },
    {
        "id": "ex2", "code_label": "Ta fonction is_move_valid()", "num": "2",
        "title": "Est-ce qu'un mouvement est valide ?",
        "unlock_after": "ex1",
        "has_launch": False,
        "instructions": [
            "On veut vérifier si un mouvement est valide, c'est-à-dire s'il respecte les règles du jeu.",
            "",
            "Un mouvement est valide si :",
            "• le poteau <code>source</code> dispose d'<b>au moins</b> un disque.",
            "• le poteau <code>destination</code> ne dispose d'<b>aucun disque</b>, ou le disque à son sommet est <b>plus grand</b> que le disque au sommet du poteau source.",
            "",
            "La fonction à <b>implémenter</b> accepte <b>trois paramètres</b> :",
            "• <code>poles</code> — les poteaux, qui contiennent des informations sur l'état du jeu.",
            "• <code>source</code> — le poteau à partir duquel déplacer le disque.",
            "• <code>destination</code> — le poteau vers lequel déplacer le disque.",
            "",
            "Elle <b>retourne</b> un booléen : <code>True</code> si le mouvement est valide, <code>False</code> sinon.",
            "",
            "<b>Exemples de code utiles :</b>",
            "<code>poles[source].num_disks == 0</code> → vaut <code>True</code> s'il n'y a aucun disque sur le poteau source.",
            "<code>poles['A'].upper_disk.width</code> → vaut <code>5.0</code> si le disque au sommet du poteau A a un diamètre de 5.",
        ],
        "starter": "def is_move_valid(poles, source, destination):\n    # Écrire votre code en dessous de ce commentaire.\n    pass\n",
        "check_setup": "from tests import check_is_move_valid\nfrom engine import Pole, Disk",
        "check_call":  "check_is_move_valid(is_move_valid)",
        "needs": [],
    },
    {
        "id": "ex3", "code_label": "Ta fonction play()", "num": "3",
        "title": "Le bot — jouer automatiquement",
        "unlock_after": "ex2",
        "has_launch": True,
        "instructions": [
            "On va maintenant implémenter une fonction <code>play()</code> qui va <b>jouer à notre place</b> !",
            "",
            "La fonction accepte les paramètres suivants :",
            "• <code>num_disks</code> — le nombre total de disques en jeu.",
            "• <code>poles</code> — les poteaux, qui contiennent des informations sur l'état du jeu.",
            "",
            "Pour jouer un coup, utilise le mot-clé <code>yield</code> :",
            "<code>yield ('A', 'B')</code> → déplace le disque du sommet du poteau A vers le sommet du poteau B.",
            "",
            "<b>Ton implémentation n'a pas besoin de vérifier si la partie est terminée, l'application s'en charge pour toi.</b>",
            "",
            "<b>Aide pour l'algorithme :</b>",
            "L'approche itérative consiste à boucler sur les paires de poteaux jusqu'à ce que la partie soit terminée.",
            "Les paires sur lesquelles boucler sont : <code>(A, B)</code> → <code>(A, C)</code> → <code>(B, C)</code> → recommencer.",
            "",
            "Pour chaque paire, si le mouvement direct est impossible, joue dans le sens inverse.",
            "Exemple avec 3 disques : A→B, A→C, B→C, A→B, C→A, C→B, A→B. Terminé !",
            "",
            "<b>N'hésite pas à utiliser <code>is_move_valid()</code> de l'exercice 2 !</b>",
        ],
        "starter": "def play(num_disks, poles):\n    # Écrire votre code en dessous de ce commentaire.\n    pass\n",
        "check_setup": None,
        "check_call":  None,
        "needs": ["ex2"],
    },
    {
        "id": "ex4", "code_label": "Tes fonctions is_game_over() et play() — version stricte", "num": "4",
        "title": "Version stricte — arrivée sur C uniquement",
        "unlock_after": "ex3_run",
        "has_launch": True,
        "instructions": [
            "Si tu as implémenté l'algorithme de l'exercice 3, tu remarqueras que dans certains cas il déplace la tour sur le poteau <b>B</b>, et dans d'autres cas sur le poteau <b>C</b>.",
            "",
            "On va se fixer une contrainte supplémentaire : la tour doit à présent être déplacée sur le poteau <b>C uniquement</b>. Le poteau B ne sert que d'intermédiaire.",
            "",
            "<b>Il y a deux choses à faire :</b>",
            "1. Mets à jour <code>is_game_over()</code> pour que la victoire soit déclarée uniquement quand tous les disques sont sur <b>C</b>.",
            "2. Adapte <code>play()</code> — l'ordre des paires dépend de la parité du nombre de disques.",
            "",
            "<b>Indice :</b>",
            "<code>if num_disks % 2 == 0:</code> → le nombre de disques est <b>pair</b>",
            "<code>else:</code> → le nombre de disques est <b>impair</b>",
            "",
            "Observe ce que donne ton algorithme de l'exercice 3 avec un nombre pair et un nombre impair de disques pour trouver le changement à appliquer.",
        ],
        "starter": "def is_game_over(poles):\n    # Écrire votre code en dessous de ce commentaire.\n    pass\n\n\ndef play(num_disks, poles):\n    # Écrire votre code en dessous de ce commentaire.\n    pass\n",
        "check_setup": "from tests import check_is_game_over\nfrom engine import Pole, Disk",
        "check_call":  "check_is_game_over(is_game_over, strict=True)",
        "needs": ["ex2"],
    },
    {
        "id": "ex5", "code_label": "Ta fonction play_rec() — version récursive", "num": "5",
        "title": "L'algorithme récursif",
        "unlock_after": "ex4_run",
        "has_launch": True,
        "instructions": [
            "Tu as codé un algorithme <b>itératif</b> (avec une boucle while). Il existe une version bien plus courte et élégante : l'algorithme <b>récursif</b>.",
            "",
            "Une fonction récursive est une fonction qui <b>s'appelle elle-même</b>.",
            "L'idée ici : pour déplacer <b>N</b> disques de <code>start</code> vers <code>end</code> en passant par <code>middle</code>, on peut décomposer le problème en 3 étapes :",
            "",
            "1. Déplace les <b>N-1</b> disques du dessus de <code>start</code> vers <code>middle</code> (en utilisant <code>end</code> comme intermédiaire)",
            "2. Déplace le <b>grand disque</b> de <code>start</code> vers <code>end</code>",
            "3. Déplace les <b>N-1</b> disques de <code>middle</code> vers <code>end</code> (en utilisant <code>start</code> comme intermédiaire)",
            "",
            "La fonction <code>play_rec()</code> prend ces paramètres :",
            "• <code>num_disks</code> — nombre de disques à déplacer",
            "• <code>poles</code> — l'état du jeu",
            "• <code>start</code> — poteau de départ (par défaut <code>'A'</code>)",
            "• <code>middle</code> — poteau intermédiaire (par défaut <code>'B'</code>)",
            "• <code>end</code> — poteau d'arrivée (par défaut <code>'C'</code>)",
            "",
            "Pour rappeler la fonction récursivement en échangeant les rôles :",
            "<code>yield from play_rec(num_disks-1, poles, start, end, middle)</code>",
            "",
            "Pour jouer le coup du grand disque : <code>yield (start, end)</code>",
            "",
            "<b>Cas de base (condition d'arrêt) :</b> si <code>num_disks == 0</code>, il n'y a rien à faire.",
        ],
        "starter": "def play_rec(num_disks, poles, start='A', middle='B', end='C'):\n    # Écrire votre code en dessous de ce commentaire.\n    pass\n",
        "check_setup": None,
        "check_call":  None,
        "needs": ["ex2"],
    },
]
